// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.12.3
// source: somewhat.proto

package v1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Something ...
type Something struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt   *timestamp.Timestamp `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (x *Something) Reset() {
	*x = Something{}
	if protoimpl.UnsafeEnabled {
		mi := &file_somewhat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Something) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Something) ProtoMessage() {}

func (x *Something) ProtoReflect() protoreflect.Message {
	mi := &file_somewhat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Something.ProtoReflect.Descriptor instead.
func (*Something) Descriptor() ([]byte, []int) {
	return file_somewhat_proto_rawDescGZIP(), []int{0}
}

func (x *Something) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Something) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Something) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Something) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// GetSomethingRequest ...
type GetSomethingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id  string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetSomethingRequest) Reset() {
	*x = GetSomethingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_somewhat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSomethingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSomethingRequest) ProtoMessage() {}

func (x *GetSomethingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_somewhat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSomethingRequest.ProtoReflect.Descriptor instead.
func (*GetSomethingRequest) Descriptor() ([]byte, []int) {
	return file_somewhat_proto_rawDescGZIP(), []int{1}
}

func (x *GetSomethingRequest) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *GetSomethingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetSomethingResponse ...
type GetSomethingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api       string     `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Something *Something `protobuf:"bytes,2,opt,name=something,proto3" json:"something,omitempty"`
}

func (x *GetSomethingResponse) Reset() {
	*x = GetSomethingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_somewhat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSomethingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSomethingResponse) ProtoMessage() {}

func (x *GetSomethingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_somewhat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSomethingResponse.ProtoReflect.Descriptor instead.
func (*GetSomethingResponse) Descriptor() ([]byte, []int) {
	return file_somewhat_proto_rawDescGZIP(), []int{2}
}

func (x *GetSomethingResponse) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *GetSomethingResponse) GetSomething() *Something {
	if x != nil {
		return x.Something
	}
	return nil
}

// UpdateSomethingRequest ...
type UpdateSomethingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api       string     `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Something *Something `protobuf:"bytes,2,opt,name=something,proto3" json:"something,omitempty"`
}

func (x *UpdateSomethingRequest) Reset() {
	*x = UpdateSomethingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_somewhat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSomethingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSomethingRequest) ProtoMessage() {}

func (x *UpdateSomethingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_somewhat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSomethingRequest.ProtoReflect.Descriptor instead.
func (*UpdateSomethingRequest) Descriptor() ([]byte, []int) {
	return file_somewhat_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSomethingRequest) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *UpdateSomethingRequest) GetSomething() *Something {
	if x != nil {
		return x.Something
	}
	return nil
}

// UpdateSomethingResponse ...
type UpdateSomethingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api     string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Updated bool   `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
}

func (x *UpdateSomethingResponse) Reset() {
	*x = UpdateSomethingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_somewhat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSomethingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSomethingResponse) ProtoMessage() {}

func (x *UpdateSomethingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_somewhat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSomethingResponse.ProtoReflect.Descriptor instead.
func (*UpdateSomethingResponse) Descriptor() ([]byte, []int) {
	return file_somewhat_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSomethingResponse) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *UpdateSomethingResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

// CreateSomethingRequest ...
type CreateSomethingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api       string     `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Something *Something `protobuf:"bytes,2,opt,name=something,proto3" json:"something,omitempty"`
}

func (x *CreateSomethingRequest) Reset() {
	*x = CreateSomethingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_somewhat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSomethingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSomethingRequest) ProtoMessage() {}

func (x *CreateSomethingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_somewhat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSomethingRequest.ProtoReflect.Descriptor instead.
func (*CreateSomethingRequest) Descriptor() ([]byte, []int) {
	return file_somewhat_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSomethingRequest) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *CreateSomethingRequest) GetSomething() *Something {
	if x != nil {
		return x.Something
	}
	return nil
}

// CreateSomethingResponse ...
type CreateSomethingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id  string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateSomethingResponse) Reset() {
	*x = CreateSomethingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_somewhat_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSomethingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSomethingResponse) ProtoMessage() {}

func (x *CreateSomethingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_somewhat_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSomethingResponse.ProtoReflect.Descriptor instead.
func (*CreateSomethingResponse) Descriptor() ([]byte, []int) {
	return file_somewhat_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSomethingResponse) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *CreateSomethingResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteSomethingRequest ...
type DeleteSomethingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id  string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteSomethingRequest) Reset() {
	*x = DeleteSomethingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_somewhat_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSomethingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSomethingRequest) ProtoMessage() {}

func (x *DeleteSomethingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_somewhat_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSomethingRequest.ProtoReflect.Descriptor instead.
func (*DeleteSomethingRequest) Descriptor() ([]byte, []int) {
	return file_somewhat_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSomethingRequest) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *DeleteSomethingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteSomethingResponse ...
type DeleteSomethingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api     string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Deleted bool   `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
}

func (x *DeleteSomethingResponse) Reset() {
	*x = DeleteSomethingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_somewhat_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSomethingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSomethingResponse) ProtoMessage() {}

func (x *DeleteSomethingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_somewhat_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSomethingResponse.ProtoReflect.Descriptor instead.
func (*DeleteSomethingResponse) Descriptor() ([]byte, []int) {
	return file_somewhat_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSomethingResponse) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *DeleteSomethingResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// ListSomethingRequest ...
type ListSomethingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
}

func (x *ListSomethingRequest) Reset() {
	*x = ListSomethingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_somewhat_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSomethingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSomethingRequest) ProtoMessage() {}

func (x *ListSomethingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_somewhat_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSomethingRequest.ProtoReflect.Descriptor instead.
func (*ListSomethingRequest) Descriptor() ([]byte, []int) {
	return file_somewhat_proto_rawDescGZIP(), []int{9}
}

func (x *ListSomethingRequest) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

// ListSomethingResponse ...
type ListSomethingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api        string       `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Somethings []*Something `protobuf:"bytes,2,rep,name=somethings,proto3" json:"somethings,omitempty"`
}

func (x *ListSomethingResponse) Reset() {
	*x = ListSomethingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_somewhat_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSomethingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSomethingResponse) ProtoMessage() {}

func (x *ListSomethingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_somewhat_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSomethingResponse.ProtoReflect.Descriptor instead.
func (*ListSomethingResponse) Descriptor() ([]byte, []int) {
	return file_somewhat_proto_rawDescGZIP(), []int{10}
}

func (x *ListSomethingResponse) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *ListSomethingResponse) GetSomethings() []*Something {
	if x != nil {
		return x.Somethings
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api      string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_somewhat_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_somewhat_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_somewhat_proto_rawDescGZIP(), []int{11}
}

func (x *LoginRequest) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_somewhat_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_somewhat_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_somewhat_proto_rawDescGZIP(), []int{12}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_somewhat_proto protoreflect.FileDescriptor

var file_somewhat_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x6f, 0x6d, 0x65, 0x77, 0x68, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x2c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d,
	0x73, 0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x8d, 0x01, 0x0a, 0x09, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x22, 0x37, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x69, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x69, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x55, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x61, 0x70, 0x69, 0x12, 0x2b, 0x0a, 0x09, 0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6f, 0x6d,
	0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x09, 0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e,
	0x67, 0x22, 0x57, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x6d, 0x65, 0x74,
	0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x70, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x69, 0x12, 0x2b, 0x0a,
	0x09, 0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x52,
	0x09, 0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x22, 0x45, 0x0a, 0x17, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x69, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x22, 0x57, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x6d, 0x65, 0x74,
	0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x70, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x69, 0x12, 0x2b, 0x0a,
	0x09, 0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x52,
	0x09, 0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x22, 0x3b, 0x0a, 0x17, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x69, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3a, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x61, 0x70, 0x69, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x45, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6f, 0x6d,
	0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x61, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x69,
	0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0x28, 0x0a, 0x14, 0x4c, 0x69,
	0x73, 0x74, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x61, 0x70, 0x69, 0x22, 0x58, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6f, 0x6d, 0x65,
	0x74, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x61, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x69, 0x12,
	0x2d, 0x0a, 0x0a, 0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69,
	0x6e, 0x67, 0x52, 0x0a, 0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x58,
	0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x61, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x69,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x25, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x32,
	0xcd, 0x04, 0x0a, 0x08, 0x53, 0x6f, 0x6d, 0x65, 0x77, 0x68, 0x61, 0x74, 0x12, 0x5d, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x12, 0x17, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6f,
	0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x12, 0x12, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x6f, 0x6d,
	0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x73, 0x0a, 0x0f, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x12, 0x1a,
	0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x27, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x21, 0x1a,
	0x1c, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x2f, 0x7b,
	0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x2e, 0x69, 0x64, 0x7d, 0x3a, 0x01, 0x2a,
	0x12, 0x64, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68,
	0x69, 0x6e, 0x67, 0x12, 0x1a, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x6d, 0x65, 0x74,
	0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x12, 0x22, 0x0d, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68,
	0x69, 0x6e, 0x67, 0x3a, 0x01, 0x2a, 0x12, 0x66, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x2a, 0x12, 0x2f, 0x76, 0x31, 0x2f,
	0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x5b,
	0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x12,
	0x18, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x76,
	0x31, 0x2f, 0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x12, 0x42, 0x0a, 0x05, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x10, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x0e, 0x22, 0x09, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x3a, 0x01, 0x2a, 0x42,
	0x8d, 0x02, 0x5a, 0x04, 0x2e, 0x3b, 0x76, 0x31, 0x92, 0x41, 0x83, 0x02, 0x12, 0x6c, 0x0a, 0x08,
	0x73, 0x6f, 0x6d, 0x65, 0x77, 0x68, 0x61, 0x74, 0x22, 0x5b, 0x0a, 0x10, 0x73, 0x6f, 0x6d, 0x65,
	0x77, 0x68, 0x61, 0x74, 0x20, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x2f, 0x68, 0x74,
	0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x64, 0x68, 0x61, 0x6e, 0x75, 0x73, 0x61, 0x70, 0x75, 0x74, 0x72, 0x61, 0x2f, 0x73, 0x6f,
	0x6d, 0x65, 0x77, 0x68, 0x61, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x16, 0x61,
	0x6e, 0x64, 0x72, 0x65, 0x61, 0x73, 0x64, 0x68, 0x61, 0x6e, 0x75, 0x40, 0x67, 0x6d, 0x61, 0x69,
	0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x32, 0x03, 0x31, 0x2e, 0x30, 0x2a, 0x01, 0x01, 0x32, 0x10, 0x61,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6a, 0x73, 0x6f, 0x6e, 0x3a,
	0x10, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6a, 0x73, 0x6f,
	0x6e, 0x52, 0x20, 0x0a, 0x03, 0x34, 0x30, 0x30, 0x12, 0x19, 0x0a, 0x0f, 0x34, 0x30, 0x30, 0x20,
	0x42, 0x61, 0x64, 0x20, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x06, 0x0a, 0x04, 0x9a,
	0x02, 0x01, 0x07, 0x52, 0x1e, 0x0a, 0x03, 0x34, 0x30, 0x34, 0x12, 0x17, 0x0a, 0x0d, 0x34, 0x30,
	0x34, 0x20, 0x4e, 0x6f, 0x74, 0x20, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x06, 0x0a, 0x04, 0x9a,
	0x02, 0x01, 0x07, 0x52, 0x2a, 0x0a, 0x03, 0x35, 0x30, 0x30, 0x12, 0x23, 0x0a, 0x19, 0x35, 0x30,
	0x30, 0x20, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x20, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x20, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x06, 0x0a, 0x04, 0x9a, 0x02, 0x01, 0x07, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_somewhat_proto_rawDescOnce sync.Once
	file_somewhat_proto_rawDescData = file_somewhat_proto_rawDesc
)

func file_somewhat_proto_rawDescGZIP() []byte {
	file_somewhat_proto_rawDescOnce.Do(func() {
		file_somewhat_proto_rawDescData = protoimpl.X.CompressGZIP(file_somewhat_proto_rawDescData)
	})
	return file_somewhat_proto_rawDescData
}

var file_somewhat_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_somewhat_proto_goTypes = []interface{}{
	(*Something)(nil),               // 0: v1.Something
	(*GetSomethingRequest)(nil),     // 1: v1.GetSomethingRequest
	(*GetSomethingResponse)(nil),    // 2: v1.GetSomethingResponse
	(*UpdateSomethingRequest)(nil),  // 3: v1.UpdateSomethingRequest
	(*UpdateSomethingResponse)(nil), // 4: v1.UpdateSomethingResponse
	(*CreateSomethingRequest)(nil),  // 5: v1.CreateSomethingRequest
	(*CreateSomethingResponse)(nil), // 6: v1.CreateSomethingResponse
	(*DeleteSomethingRequest)(nil),  // 7: v1.DeleteSomethingRequest
	(*DeleteSomethingResponse)(nil), // 8: v1.DeleteSomethingResponse
	(*ListSomethingRequest)(nil),    // 9: v1.ListSomethingRequest
	(*ListSomethingResponse)(nil),   // 10: v1.ListSomethingResponse
	(*LoginRequest)(nil),            // 11: v1.LoginRequest
	(*LoginResponse)(nil),           // 12: v1.LoginResponse
	(*timestamp.Timestamp)(nil),     // 13: google.protobuf.Timestamp
}
var file_somewhat_proto_depIdxs = []int32{
	13, // 0: v1.Something.createdAt:type_name -> google.protobuf.Timestamp
	0,  // 1: v1.GetSomethingResponse.something:type_name -> v1.Something
	0,  // 2: v1.UpdateSomethingRequest.something:type_name -> v1.Something
	0,  // 3: v1.CreateSomethingRequest.something:type_name -> v1.Something
	0,  // 4: v1.ListSomethingResponse.somethings:type_name -> v1.Something
	1,  // 5: v1.Somewhat.GetSomething:input_type -> v1.GetSomethingRequest
	3,  // 6: v1.Somewhat.UpdateSomething:input_type -> v1.UpdateSomethingRequest
	5,  // 7: v1.Somewhat.CreateSomething:input_type -> v1.CreateSomethingRequest
	7,  // 8: v1.Somewhat.DeleteSomething:input_type -> v1.DeleteSomethingRequest
	9,  // 9: v1.Somewhat.ListSomething:input_type -> v1.ListSomethingRequest
	11, // 10: v1.Somewhat.Login:input_type -> v1.LoginRequest
	2,  // 11: v1.Somewhat.GetSomething:output_type -> v1.GetSomethingResponse
	4,  // 12: v1.Somewhat.UpdateSomething:output_type -> v1.UpdateSomethingResponse
	6,  // 13: v1.Somewhat.CreateSomething:output_type -> v1.CreateSomethingResponse
	8,  // 14: v1.Somewhat.DeleteSomething:output_type -> v1.DeleteSomethingResponse
	10, // 15: v1.Somewhat.ListSomething:output_type -> v1.ListSomethingResponse
	12, // 16: v1.Somewhat.Login:output_type -> v1.LoginResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_somewhat_proto_init() }
func file_somewhat_proto_init() {
	if File_somewhat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_somewhat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Something); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_somewhat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSomethingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_somewhat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSomethingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_somewhat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSomethingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_somewhat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSomethingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_somewhat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSomethingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_somewhat_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSomethingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_somewhat_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSomethingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_somewhat_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSomethingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_somewhat_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSomethingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_somewhat_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSomethingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_somewhat_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_somewhat_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_somewhat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_somewhat_proto_goTypes,
		DependencyIndexes: file_somewhat_proto_depIdxs,
		MessageInfos:      file_somewhat_proto_msgTypes,
	}.Build()
	File_somewhat_proto = out.File
	file_somewhat_proto_rawDesc = nil
	file_somewhat_proto_goTypes = nil
	file_somewhat_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SomewhatClient is the client API for Somewhat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SomewhatClient interface {
	// GetSomething ...
	GetSomething(ctx context.Context, in *GetSomethingRequest, opts ...grpc.CallOption) (*GetSomethingResponse, error)
	// UpdateSomething ...
	UpdateSomething(ctx context.Context, in *UpdateSomethingRequest, opts ...grpc.CallOption) (*UpdateSomethingResponse, error)
	// CreateSomething ...
	CreateSomething(ctx context.Context, in *CreateSomethingRequest, opts ...grpc.CallOption) (*CreateSomethingResponse, error)
	// DeleteSomething ...
	DeleteSomething(ctx context.Context, in *DeleteSomethingRequest, opts ...grpc.CallOption) (*DeleteSomethingResponse, error)
	// ListSomething ...
	ListSomething(ctx context.Context, in *ListSomethingRequest, opts ...grpc.CallOption) (*ListSomethingResponse, error)
	// Login ...
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type somewhatClient struct {
	cc grpc.ClientConnInterface
}

func NewSomewhatClient(cc grpc.ClientConnInterface) SomewhatClient {
	return &somewhatClient{cc}
}

func (c *somewhatClient) GetSomething(ctx context.Context, in *GetSomethingRequest, opts ...grpc.CallOption) (*GetSomethingResponse, error) {
	out := new(GetSomethingResponse)
	err := c.cc.Invoke(ctx, "/v1.Somewhat/GetSomething", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *somewhatClient) UpdateSomething(ctx context.Context, in *UpdateSomethingRequest, opts ...grpc.CallOption) (*UpdateSomethingResponse, error) {
	out := new(UpdateSomethingResponse)
	err := c.cc.Invoke(ctx, "/v1.Somewhat/UpdateSomething", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *somewhatClient) CreateSomething(ctx context.Context, in *CreateSomethingRequest, opts ...grpc.CallOption) (*CreateSomethingResponse, error) {
	out := new(CreateSomethingResponse)
	err := c.cc.Invoke(ctx, "/v1.Somewhat/CreateSomething", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *somewhatClient) DeleteSomething(ctx context.Context, in *DeleteSomethingRequest, opts ...grpc.CallOption) (*DeleteSomethingResponse, error) {
	out := new(DeleteSomethingResponse)
	err := c.cc.Invoke(ctx, "/v1.Somewhat/DeleteSomething", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *somewhatClient) ListSomething(ctx context.Context, in *ListSomethingRequest, opts ...grpc.CallOption) (*ListSomethingResponse, error) {
	out := new(ListSomethingResponse)
	err := c.cc.Invoke(ctx, "/v1.Somewhat/ListSomething", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *somewhatClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/v1.Somewhat/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SomewhatServer is the server API for Somewhat service.
type SomewhatServer interface {
	// GetSomething ...
	GetSomething(context.Context, *GetSomethingRequest) (*GetSomethingResponse, error)
	// UpdateSomething ...
	UpdateSomething(context.Context, *UpdateSomethingRequest) (*UpdateSomethingResponse, error)
	// CreateSomething ...
	CreateSomething(context.Context, *CreateSomethingRequest) (*CreateSomethingResponse, error)
	// DeleteSomething ...
	DeleteSomething(context.Context, *DeleteSomethingRequest) (*DeleteSomethingResponse, error)
	// ListSomething ...
	ListSomething(context.Context, *ListSomethingRequest) (*ListSomethingResponse, error)
	// Login ...
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
}

// UnimplementedSomewhatServer can be embedded to have forward compatible implementations.
type UnimplementedSomewhatServer struct {
}

func (*UnimplementedSomewhatServer) GetSomething(context.Context, *GetSomethingRequest) (*GetSomethingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSomething not implemented")
}
func (*UnimplementedSomewhatServer) UpdateSomething(context.Context, *UpdateSomethingRequest) (*UpdateSomethingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSomething not implemented")
}
func (*UnimplementedSomewhatServer) CreateSomething(context.Context, *CreateSomethingRequest) (*CreateSomethingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSomething not implemented")
}
func (*UnimplementedSomewhatServer) DeleteSomething(context.Context, *DeleteSomethingRequest) (*DeleteSomethingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSomething not implemented")
}
func (*UnimplementedSomewhatServer) ListSomething(context.Context, *ListSomethingRequest) (*ListSomethingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSomething not implemented")
}
func (*UnimplementedSomewhatServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}

func RegisterSomewhatServer(s *grpc.Server, srv SomewhatServer) {
	s.RegisterService(&_Somewhat_serviceDesc, srv)
}

func _Somewhat_GetSomething_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSomethingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SomewhatServer).GetSomething(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Somewhat/GetSomething",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SomewhatServer).GetSomething(ctx, req.(*GetSomethingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Somewhat_UpdateSomething_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSomethingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SomewhatServer).UpdateSomething(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Somewhat/UpdateSomething",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SomewhatServer).UpdateSomething(ctx, req.(*UpdateSomethingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Somewhat_CreateSomething_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSomethingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SomewhatServer).CreateSomething(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Somewhat/CreateSomething",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SomewhatServer).CreateSomething(ctx, req.(*CreateSomethingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Somewhat_DeleteSomething_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSomethingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SomewhatServer).DeleteSomething(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Somewhat/DeleteSomething",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SomewhatServer).DeleteSomething(ctx, req.(*DeleteSomethingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Somewhat_ListSomething_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSomethingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SomewhatServer).ListSomething(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Somewhat/ListSomething",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SomewhatServer).ListSomething(ctx, req.(*ListSomethingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Somewhat_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SomewhatServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Somewhat/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SomewhatServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Somewhat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Somewhat",
	HandlerType: (*SomewhatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSomething",
			Handler:    _Somewhat_GetSomething_Handler,
		},
		{
			MethodName: "UpdateSomething",
			Handler:    _Somewhat_UpdateSomething_Handler,
		},
		{
			MethodName: "CreateSomething",
			Handler:    _Somewhat_CreateSomething_Handler,
		},
		{
			MethodName: "DeleteSomething",
			Handler:    _Somewhat_DeleteSomething_Handler,
		},
		{
			MethodName: "ListSomething",
			Handler:    _Somewhat_ListSomething_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Somewhat_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "somewhat.proto",
}
