// Code generated by protoc-gen-go. DO NOT EDIT.
// source: somewhat.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Something ...
type Something struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Something) Reset()         { *m = Something{} }
func (m *Something) String() string { return proto.CompactTextString(m) }
func (*Something) ProtoMessage()    {}
func (*Something) Descriptor() ([]byte, []int) {
	return fileDescriptor_409ec1084c1fea67, []int{0}
}

func (m *Something) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Something.Unmarshal(m, b)
}
func (m *Something) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Something.Marshal(b, m, deterministic)
}
func (m *Something) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Something.Merge(m, src)
}
func (m *Something) XXX_Size() int {
	return xxx_messageInfo_Something.Size(m)
}
func (m *Something) XXX_DiscardUnknown() {
	xxx_messageInfo_Something.DiscardUnknown(m)
}

var xxx_messageInfo_Something proto.InternalMessageInfo

func (m *Something) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Something) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Something) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Something) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

// GetSomethingRequest ...
type GetSomethingRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSomethingRequest) Reset()         { *m = GetSomethingRequest{} }
func (m *GetSomethingRequest) String() string { return proto.CompactTextString(m) }
func (*GetSomethingRequest) ProtoMessage()    {}
func (*GetSomethingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_409ec1084c1fea67, []int{1}
}

func (m *GetSomethingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSomethingRequest.Unmarshal(m, b)
}
func (m *GetSomethingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSomethingRequest.Marshal(b, m, deterministic)
}
func (m *GetSomethingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSomethingRequest.Merge(m, src)
}
func (m *GetSomethingRequest) XXX_Size() int {
	return xxx_messageInfo_GetSomethingRequest.Size(m)
}
func (m *GetSomethingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSomethingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSomethingRequest proto.InternalMessageInfo

func (m *GetSomethingRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetSomethingRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// GetSomethingResponse ...
type GetSomethingResponse struct {
	Api                  string     `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Something            *Something `protobuf:"bytes,2,opt,name=something,proto3" json:"something,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetSomethingResponse) Reset()         { *m = GetSomethingResponse{} }
func (m *GetSomethingResponse) String() string { return proto.CompactTextString(m) }
func (*GetSomethingResponse) ProtoMessage()    {}
func (*GetSomethingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_409ec1084c1fea67, []int{2}
}

func (m *GetSomethingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSomethingResponse.Unmarshal(m, b)
}
func (m *GetSomethingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSomethingResponse.Marshal(b, m, deterministic)
}
func (m *GetSomethingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSomethingResponse.Merge(m, src)
}
func (m *GetSomethingResponse) XXX_Size() int {
	return xxx_messageInfo_GetSomethingResponse.Size(m)
}
func (m *GetSomethingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSomethingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSomethingResponse proto.InternalMessageInfo

func (m *GetSomethingResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetSomethingResponse) GetSomething() *Something {
	if m != nil {
		return m.Something
	}
	return nil
}

// UpdateSomethingRequest ...
type UpdateSomethingRequest struct {
	Api                  string     `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Something            *Something `protobuf:"bytes,2,opt,name=something,proto3" json:"something,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateSomethingRequest) Reset()         { *m = UpdateSomethingRequest{} }
func (m *UpdateSomethingRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSomethingRequest) ProtoMessage()    {}
func (*UpdateSomethingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_409ec1084c1fea67, []int{3}
}

func (m *UpdateSomethingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSomethingRequest.Unmarshal(m, b)
}
func (m *UpdateSomethingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSomethingRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSomethingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSomethingRequest.Merge(m, src)
}
func (m *UpdateSomethingRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSomethingRequest.Size(m)
}
func (m *UpdateSomethingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSomethingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSomethingRequest proto.InternalMessageInfo

func (m *UpdateSomethingRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpdateSomethingRequest) GetSomething() *Something {
	if m != nil {
		return m.Something
	}
	return nil
}

// UpdateSomethingResponse ...
type UpdateSomethingResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Updated              bool     `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSomethingResponse) Reset()         { *m = UpdateSomethingResponse{} }
func (m *UpdateSomethingResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSomethingResponse) ProtoMessage()    {}
func (*UpdateSomethingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_409ec1084c1fea67, []int{4}
}

func (m *UpdateSomethingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSomethingResponse.Unmarshal(m, b)
}
func (m *UpdateSomethingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSomethingResponse.Marshal(b, m, deterministic)
}
func (m *UpdateSomethingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSomethingResponse.Merge(m, src)
}
func (m *UpdateSomethingResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateSomethingResponse.Size(m)
}
func (m *UpdateSomethingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSomethingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSomethingResponse proto.InternalMessageInfo

func (m *UpdateSomethingResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpdateSomethingResponse) GetUpdated() bool {
	if m != nil {
		return m.Updated
	}
	return false
}

// CreateSomethingRequest ...
type CreateSomethingRequest struct {
	Api                  string     `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Something            *Something `protobuf:"bytes,2,opt,name=something,proto3" json:"something,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateSomethingRequest) Reset()         { *m = CreateSomethingRequest{} }
func (m *CreateSomethingRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSomethingRequest) ProtoMessage()    {}
func (*CreateSomethingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_409ec1084c1fea67, []int{5}
}

func (m *CreateSomethingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSomethingRequest.Unmarshal(m, b)
}
func (m *CreateSomethingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSomethingRequest.Marshal(b, m, deterministic)
}
func (m *CreateSomethingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSomethingRequest.Merge(m, src)
}
func (m *CreateSomethingRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSomethingRequest.Size(m)
}
func (m *CreateSomethingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSomethingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSomethingRequest proto.InternalMessageInfo

func (m *CreateSomethingRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateSomethingRequest) GetSomething() *Something {
	if m != nil {
		return m.Something
	}
	return nil
}

// CreateSomethingResponse ...
type CreateSomethingResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSomethingResponse) Reset()         { *m = CreateSomethingResponse{} }
func (m *CreateSomethingResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSomethingResponse) ProtoMessage()    {}
func (*CreateSomethingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_409ec1084c1fea67, []int{6}
}

func (m *CreateSomethingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSomethingResponse.Unmarshal(m, b)
}
func (m *CreateSomethingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSomethingResponse.Marshal(b, m, deterministic)
}
func (m *CreateSomethingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSomethingResponse.Merge(m, src)
}
func (m *CreateSomethingResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSomethingResponse.Size(m)
}
func (m *CreateSomethingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSomethingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSomethingResponse proto.InternalMessageInfo

func (m *CreateSomethingResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateSomethingResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// DeleteSomethingRequest ...
type DeleteSomethingRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSomethingRequest) Reset()         { *m = DeleteSomethingRequest{} }
func (m *DeleteSomethingRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSomethingRequest) ProtoMessage()    {}
func (*DeleteSomethingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_409ec1084c1fea67, []int{7}
}

func (m *DeleteSomethingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSomethingRequest.Unmarshal(m, b)
}
func (m *DeleteSomethingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSomethingRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSomethingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSomethingRequest.Merge(m, src)
}
func (m *DeleteSomethingRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSomethingRequest.Size(m)
}
func (m *DeleteSomethingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSomethingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSomethingRequest proto.InternalMessageInfo

func (m *DeleteSomethingRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteSomethingRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// DeleteSomethingResponse ...
type DeleteSomethingResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Deleted              bool     `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSomethingResponse) Reset()         { *m = DeleteSomethingResponse{} }
func (m *DeleteSomethingResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSomethingResponse) ProtoMessage()    {}
func (*DeleteSomethingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_409ec1084c1fea67, []int{8}
}

func (m *DeleteSomethingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSomethingResponse.Unmarshal(m, b)
}
func (m *DeleteSomethingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSomethingResponse.Marshal(b, m, deterministic)
}
func (m *DeleteSomethingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSomethingResponse.Merge(m, src)
}
func (m *DeleteSomethingResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSomethingResponse.Size(m)
}
func (m *DeleteSomethingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSomethingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSomethingResponse proto.InternalMessageInfo

func (m *DeleteSomethingResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteSomethingResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

// ListSomethingRequest ...
type ListSomethingRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSomethingRequest) Reset()         { *m = ListSomethingRequest{} }
func (m *ListSomethingRequest) String() string { return proto.CompactTextString(m) }
func (*ListSomethingRequest) ProtoMessage()    {}
func (*ListSomethingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_409ec1084c1fea67, []int{9}
}

func (m *ListSomethingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSomethingRequest.Unmarshal(m, b)
}
func (m *ListSomethingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSomethingRequest.Marshal(b, m, deterministic)
}
func (m *ListSomethingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSomethingRequest.Merge(m, src)
}
func (m *ListSomethingRequest) XXX_Size() int {
	return xxx_messageInfo_ListSomethingRequest.Size(m)
}
func (m *ListSomethingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSomethingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSomethingRequest proto.InternalMessageInfo

func (m *ListSomethingRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

// ListSomethingResponse ...
type ListSomethingResponse struct {
	Api                  string       `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Somethings           []*Something `protobuf:"bytes,2,rep,name=somethings,proto3" json:"somethings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListSomethingResponse) Reset()         { *m = ListSomethingResponse{} }
func (m *ListSomethingResponse) String() string { return proto.CompactTextString(m) }
func (*ListSomethingResponse) ProtoMessage()    {}
func (*ListSomethingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_409ec1084c1fea67, []int{10}
}

func (m *ListSomethingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSomethingResponse.Unmarshal(m, b)
}
func (m *ListSomethingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSomethingResponse.Marshal(b, m, deterministic)
}
func (m *ListSomethingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSomethingResponse.Merge(m, src)
}
func (m *ListSomethingResponse) XXX_Size() int {
	return xxx_messageInfo_ListSomethingResponse.Size(m)
}
func (m *ListSomethingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSomethingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSomethingResponse proto.InternalMessageInfo

func (m *ListSomethingResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ListSomethingResponse) GetSomethings() []*Something {
	if m != nil {
		return m.Somethings
	}
	return nil
}

func init() {
	proto.RegisterType((*Something)(nil), "v1.Something")
	proto.RegisterType((*GetSomethingRequest)(nil), "v1.GetSomethingRequest")
	proto.RegisterType((*GetSomethingResponse)(nil), "v1.GetSomethingResponse")
	proto.RegisterType((*UpdateSomethingRequest)(nil), "v1.UpdateSomethingRequest")
	proto.RegisterType((*UpdateSomethingResponse)(nil), "v1.UpdateSomethingResponse")
	proto.RegisterType((*CreateSomethingRequest)(nil), "v1.CreateSomethingRequest")
	proto.RegisterType((*CreateSomethingResponse)(nil), "v1.CreateSomethingResponse")
	proto.RegisterType((*DeleteSomethingRequest)(nil), "v1.DeleteSomethingRequest")
	proto.RegisterType((*DeleteSomethingResponse)(nil), "v1.DeleteSomethingResponse")
	proto.RegisterType((*ListSomethingRequest)(nil), "v1.ListSomethingRequest")
	proto.RegisterType((*ListSomethingResponse)(nil), "v1.ListSomethingResponse")
}

func init() {
	proto.RegisterFile("somewhat.proto", fileDescriptor_409ec1084c1fea67)
}

var fileDescriptor_409ec1084c1fea67 = []byte{
	// 429 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xcf, 0x8f, 0x9a, 0x40,
	0x14, 0xc7, 0x03, 0xf6, 0x87, 0x3c, 0xab, 0x36, 0x53, 0x2b, 0x94, 0x1e, 0x4a, 0x38, 0x99, 0x34,
	0xc5, 0x68, 0x0f, 0x6d, 0xda, 0x93, 0xa9, 0xa6, 0x89, 0xe9, 0x09, 0x6b, 0x76, 0xaf, 0x28, 0xb3,
	0x3a, 0x89, 0x38, 0xac, 0x33, 0xba, 0x7f, 0xc5, 0xfe, 0xbd, 0x7b, 0xdd, 0x30, 0x03, 0xa2, 0x30,
	0x6c, 0xdc, 0x64, 0x6f, 0xce, 0xbc, 0xef, 0xfb, 0xfa, 0xe1, 0xbd, 0x2f, 0x40, 0x8b, 0xd1, 0x08,
	0xdf, 0xad, 0x03, 0xee, 0xc5, 0x3b, 0xca, 0x29, 0xd2, 0x0f, 0x03, 0xfb, 0xcb, 0x8a, 0xd2, 0xd5,
	0x06, 0xf7, 0xc5, 0xcd, 0x62, 0x7f, 0xd3, 0xe7, 0x24, 0xc2, 0x8c, 0x07, 0x51, 0x2c, 0x45, 0xee,
	0xbd, 0x06, 0xc6, 0x8c, 0x46, 0x98, 0xaf, 0xc9, 0x76, 0x85, 0x5a, 0xa0, 0x93, 0xd0, 0xd2, 0x1c,
	0xad, 0x67, 0xf8, 0x3a, 0x09, 0x51, 0x07, 0x5e, 0x73, 0xc2, 0x37, 0xd8, 0xd2, 0xc5, 0x95, 0x3c,
	0x20, 0x07, 0x1a, 0x21, 0x66, 0xcb, 0x1d, 0x89, 0x39, 0xa1, 0x5b, 0xab, 0x26, 0x6a, 0xa7, 0x57,
	0xe8, 0x27, 0x18, 0xcb, 0x1d, 0x0e, 0x38, 0x0e, 0x47, 0xdc, 0x7a, 0xe5, 0x68, 0xbd, 0xc6, 0xd0,
	0xf6, 0x24, 0x8a, 0x97, 0xa1, 0x78, 0xff, 0x33, 0x14, 0x3f, 0x17, 0xbb, 0x3f, 0xe0, 0xc3, 0x5f,
	0xcc, 0x8f, 0x44, 0x3e, 0xbe, 0xdd, 0x63, 0xc6, 0xd1, 0x7b, 0xa8, 0x05, 0x31, 0x49, 0xc9, 0x92,
	0x9f, 0x29, 0xaa, 0x9e, 0xa1, 0xba, 0x73, 0xe8, 0x9c, 0x37, 0xb2, 0x98, 0x6e, 0x19, 0x56, 0x74,
	0x7e, 0x05, 0x83, 0x65, 0x32, 0x61, 0xd0, 0x18, 0x36, 0xbd, 0xc3, 0xc0, 0xcb, 0x7b, 0xf3, 0xba,
	0x7b, 0x05, 0xdd, 0x79, 0x1c, 0x06, 0x1c, 0x5f, 0x80, 0xf4, 0x2c, 0xe3, 0x09, 0x98, 0x25, 0xe3,
	0x4a, 0x64, 0x0b, 0xde, 0xee, 0x85, 0x58, 0x3e, 0x71, 0xdd, 0xcf, 0x8e, 0x09, 0xdf, 0x1f, 0x31,
	0xbc, 0x97, 0xe6, 0xfb, 0x0d, 0x66, 0xc9, 0xb8, 0x92, 0xaf, 0xb8, 0x8c, 0x5f, 0xd0, 0x1d, 0xe3,
	0x0d, 0xbe, 0x88, 0xaa, 0xd8, 0x3b, 0x01, 0xb3, 0xd4, 0xfb, 0xd4, 0x60, 0x42, 0x21, 0x3e, 0x0e,
	0x26, 0x3d, 0xba, 0x3d, 0xe8, 0xfc, 0x23, 0xec, 0x82, 0x24, 0xb9, 0xd7, 0xf0, 0xb1, 0xa0, 0xac,
	0xfc, 0xbb, 0x6f, 0x00, 0xc7, 0x09, 0x31, 0x4b, 0x77, 0x6a, 0xe5, 0x11, 0x9e, 0x08, 0x86, 0x0f,
	0x3a, 0xd4, 0x67, 0xe9, 0x4b, 0x89, 0x46, 0xf0, 0xee, 0x34, 0xa0, 0xc8, 0x4c, 0xfa, 0x14, 0x59,
	0xb7, 0xad, 0x72, 0x21, 0x05, 0x9a, 0x42, 0xbb, 0x90, 0x19, 0x64, 0x27, 0x62, 0x75, 0x42, 0xed,
	0xcf, 0xca, 0x5a, 0xee, 0x55, 0xd8, 0xaf, 0xf4, 0x52, 0xa7, 0x49, 0x7a, 0x55, 0x05, 0x62, 0x0a,
	0xed, 0xc2, 0xca, 0xa4, 0x97, 0x3a, 0x03, 0xd2, 0xab, 0x6a, 0xc7, 0x63, 0x68, 0x9e, 0x6d, 0x03,
	0x89, 0x71, 0xa8, 0x56, 0x69, 0x7f, 0x52, 0x54, 0xa4, 0xcb, 0xe2, 0x8d, 0xf8, 0xca, 0x7c, 0x7f,
	0x0c, 0x00, 0x00, 0xff, 0xff, 0x73, 0x37, 0xfd, 0x5d, 0x14, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SomewhatClient is the client API for Somewhat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SomewhatClient interface {
	// GetSomething ...
	GetSomething(ctx context.Context, in *GetSomethingRequest, opts ...grpc.CallOption) (*GetSomethingResponse, error)
	// UpdateSomething ...
	UpdateSomething(ctx context.Context, in *UpdateSomethingRequest, opts ...grpc.CallOption) (*UpdateSomethingResponse, error)
	// CreateSomething ...
	CreateSomething(ctx context.Context, in *CreateSomethingRequest, opts ...grpc.CallOption) (*CreateSomethingResponse, error)
	// DeleteSomething ...
	DeleteSomething(ctx context.Context, in *DeleteSomethingRequest, opts ...grpc.CallOption) (*DeleteSomethingResponse, error)
	// ListSomething ...
	ListSomething(ctx context.Context, in *ListSomethingRequest, opts ...grpc.CallOption) (*ListSomethingResponse, error)
}

type somewhatClient struct {
	cc grpc.ClientConnInterface
}

func NewSomewhatClient(cc grpc.ClientConnInterface) SomewhatClient {
	return &somewhatClient{cc}
}

func (c *somewhatClient) GetSomething(ctx context.Context, in *GetSomethingRequest, opts ...grpc.CallOption) (*GetSomethingResponse, error) {
	out := new(GetSomethingResponse)
	err := c.cc.Invoke(ctx, "/v1.Somewhat/GetSomething", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *somewhatClient) UpdateSomething(ctx context.Context, in *UpdateSomethingRequest, opts ...grpc.CallOption) (*UpdateSomethingResponse, error) {
	out := new(UpdateSomethingResponse)
	err := c.cc.Invoke(ctx, "/v1.Somewhat/UpdateSomething", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *somewhatClient) CreateSomething(ctx context.Context, in *CreateSomethingRequest, opts ...grpc.CallOption) (*CreateSomethingResponse, error) {
	out := new(CreateSomethingResponse)
	err := c.cc.Invoke(ctx, "/v1.Somewhat/CreateSomething", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *somewhatClient) DeleteSomething(ctx context.Context, in *DeleteSomethingRequest, opts ...grpc.CallOption) (*DeleteSomethingResponse, error) {
	out := new(DeleteSomethingResponse)
	err := c.cc.Invoke(ctx, "/v1.Somewhat/DeleteSomething", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *somewhatClient) ListSomething(ctx context.Context, in *ListSomethingRequest, opts ...grpc.CallOption) (*ListSomethingResponse, error) {
	out := new(ListSomethingResponse)
	err := c.cc.Invoke(ctx, "/v1.Somewhat/ListSomething", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SomewhatServer is the server API for Somewhat service.
type SomewhatServer interface {
	// GetSomething ...
	GetSomething(context.Context, *GetSomethingRequest) (*GetSomethingResponse, error)
	// UpdateSomething ...
	UpdateSomething(context.Context, *UpdateSomethingRequest) (*UpdateSomethingResponse, error)
	// CreateSomething ...
	CreateSomething(context.Context, *CreateSomethingRequest) (*CreateSomethingResponse, error)
	// DeleteSomething ...
	DeleteSomething(context.Context, *DeleteSomethingRequest) (*DeleteSomethingResponse, error)
	// ListSomething ...
	ListSomething(context.Context, *ListSomethingRequest) (*ListSomethingResponse, error)
}

// UnimplementedSomewhatServer can be embedded to have forward compatible implementations.
type UnimplementedSomewhatServer struct {
}

func (*UnimplementedSomewhatServer) GetSomething(ctx context.Context, req *GetSomethingRequest) (*GetSomethingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSomething not implemented")
}
func (*UnimplementedSomewhatServer) UpdateSomething(ctx context.Context, req *UpdateSomethingRequest) (*UpdateSomethingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSomething not implemented")
}
func (*UnimplementedSomewhatServer) CreateSomething(ctx context.Context, req *CreateSomethingRequest) (*CreateSomethingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSomething not implemented")
}
func (*UnimplementedSomewhatServer) DeleteSomething(ctx context.Context, req *DeleteSomethingRequest) (*DeleteSomethingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSomething not implemented")
}
func (*UnimplementedSomewhatServer) ListSomething(ctx context.Context, req *ListSomethingRequest) (*ListSomethingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSomething not implemented")
}

func RegisterSomewhatServer(s *grpc.Server, srv SomewhatServer) {
	s.RegisterService(&_Somewhat_serviceDesc, srv)
}

func _Somewhat_GetSomething_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSomethingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SomewhatServer).GetSomething(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Somewhat/GetSomething",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SomewhatServer).GetSomething(ctx, req.(*GetSomethingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Somewhat_UpdateSomething_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSomethingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SomewhatServer).UpdateSomething(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Somewhat/UpdateSomething",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SomewhatServer).UpdateSomething(ctx, req.(*UpdateSomethingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Somewhat_CreateSomething_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSomethingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SomewhatServer).CreateSomething(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Somewhat/CreateSomething",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SomewhatServer).CreateSomething(ctx, req.(*CreateSomethingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Somewhat_DeleteSomething_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSomethingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SomewhatServer).DeleteSomething(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Somewhat/DeleteSomething",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SomewhatServer).DeleteSomething(ctx, req.(*DeleteSomethingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Somewhat_ListSomething_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSomethingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SomewhatServer).ListSomething(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Somewhat/ListSomething",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SomewhatServer).ListSomething(ctx, req.(*ListSomethingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Somewhat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Somewhat",
	HandlerType: (*SomewhatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSomething",
			Handler:    _Somewhat_GetSomething_Handler,
		},
		{
			MethodName: "UpdateSomething",
			Handler:    _Somewhat_UpdateSomething_Handler,
		},
		{
			MethodName: "CreateSomething",
			Handler:    _Somewhat_CreateSomething_Handler,
		},
		{
			MethodName: "DeleteSomething",
			Handler:    _Somewhat_DeleteSomething_Handler,
		},
		{
			MethodName: "ListSomething",
			Handler:    _Somewhat_ListSomething_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "somewhat.proto",
}
