// Code generated by mockery v1.0.0. DO NOT EDIT.

package testutil

import mock "github.com/stretchr/testify/mock"

// MockTearDownInterface is an autogenerated mock type for the TearDownInterface type
type MockTearDownInterface struct {
	mock.Mock
}

// Restore provides a mock function with given fields:
func (_m *MockTearDownInterface) Restore() {
	_m.Called()
}
